package com.likeminds.chatmm.utils.model

import androidx.annotation.IntDef

const val ITEM_NONE = 0
const val ITEM_MEMBER = 1
const val ITEM_CONVERSATION_POLL = 2
const val ITEM_CHATROOM_IMAGE = 3
const val ITEM_CHATROOM_PDF = 4
const val ITEM_MEDIA_PICKER_FOLDER = 5
const val ITEM_REPORT_TAG = 6
const val ITEM_CREATE_POLL = 7
const val ITEM_POLL = 8

const val ITEM_MEDIA_PICKER_SINGLE = 9
const val ITEM_MEDIA_PICKER_HEADER = 10
const val ITEM_MEDIA_PICKER_BROWSE = 11
const val ITEM_MEDIA_PICKER_DOCUMENT = 12
const val ITEM_CHAT_ROOM = 13
const val ITEM_CONVERSATION_ACTION = 14
const val ITEM_CONVERSATION = 15
const val ITEM_CONVERSATION_FOLLOW = 16
const val ITEM_CONVERSATION_SINGLE_IMAGE = 17
const val ITEM_IMAGE = 18
const val ITEM_PDF = 19
const val ITEM_IMAGE_EXPANDED = 20
const val ITEM_PDF_EXPANDED = 21
const val ITEM_MEDIA_SMALL = 22
const val ITEM_CONVERSATION_MULTIPLE_MEDIA = 23
const val ITEM_CONVERSATION_SINGLE_PDF = 24
const val ITEM_CONVERSATION_LINK = 25
const val ITEM_CHATROOM_DATE = 26
const val ITEM_POLL_MORE_OPTIONS = 27
const val ITEM_IMAGE_SWIPE = 28
const val ITEM_HOME_CHAT_ROOM = 29
const val ITEM_DOCUMENT_SMALL = 30
const val ITEM_EMPTY_VIEW = 31
const val ITEM_CONVERSATION_AUTO_FOLLOWED_TAGGED_CHAT_ROOM = 32
const val ITEM_CHAT_ROOM_ANNOUNCEMENT = 33
const val ITEM_MEMBER_ACTION = 34
const val ITEM_MANAGEMENT_RIGHT_PERMISSION = 35
const val ITEM_CHATROOM_VIDEO = 36
const val ITEM_CONVERSATION_SINGLE_VIDEO = 37
const val ITEM_VIDEO = 38
const val ITEM_VIDEO_SWIPE = 39
const val ITEM_VIDEO_EXPANDED = 40
const val ITEM_CONTENT_HEADER_VIEW = 41
const val ITEM_HOME_LINE_BREAK_VIEW = 42
const val ITEM_HOME_BLANK_SPACE_VIEW = 43
const val ITEM_CHATROOM_LIST_SHIMMER_VIEW = 44
const val ITEM_SEARCH_CHATROOM = 45
const val ITEM_NO_SEARCH_RESULTS_VIEW = 46
const val ITEM_SEARCH_CONTENT_HEADER_VIEW = 47
const val ITEM_SEARCH_LINE_BREAK_VIEW = 48
const val ITEM_SEARCH_MESSAGE = 49
const val ITEM_CONVERSATION_LIST_SHIMMER_VIEW = 50
const val ITEM_MESSAGE_REACTION = 51
const val ITEM_CONVERSATION_SINGLE_GIF = 52
const val ITEM_SEARCH_TITLE = 53
const val ITEM_SINGLE_SHIMMER = 54
const val ITEM_OVERFLOW_MENU_ITEM = 55
const val ITEM_CONVERSATION_MULTIPLE_DOCUMENT = 56
const val ITEM_DOCUMENT = 57
const val ITEM_MEDIA_PICKER_AUDIO = 58
const val ITEM_AUDIO_SMALL = 59
const val ITEM_CONVERSATION_AUDIO = 60
const val ITEM_AUDIO = 61
const val ITEM_CREATE_CHATROOM_AUDIO = 62
const val ITEM_CONVERSATION_VOICE_NOTE = 63
const val ITEM_VIEW_PARTICIPANTS = 64
const val ITEM_POLL_RESULT_USER = 65
const val ITEM_HOME_FEED = 66
const val ITEM_EXPLORE = 67
const val ITEM_DM_FEED_EMPTY_DATA = 68
const val ITEM_DIRECT_MESSAGE = 69
const val ITEM_COMMUNITY_MEMBER = 70
const val ITEM_CHANNEL_INVITE = 71

//for custom widgets
const val ITEM_CONVERSATION_CUSTOM_WIDGET = 1001

@IntDef(
    ITEM_NONE,
    ITEM_MEMBER,
    ITEM_CONVERSATION_POLL,
    ITEM_MEDIA_PICKER_FOLDER,
    ITEM_CONVERSATION_AUTO_FOLLOWED_TAGGED_CHAT_ROOM,
    ITEM_REPORT_TAG,
    ITEM_CREATE_POLL,
    ITEM_POLL,
    ITEM_MEDIA_PICKER_SINGLE,
    ITEM_MEDIA_PICKER_HEADER,
    ITEM_MEDIA_PICKER_BROWSE,
    ITEM_MEDIA_PICKER_DOCUMENT,
    ITEM_CHAT_ROOM,
    ITEM_CONVERSATION_ACTION,
    ITEM_CONVERSATION,
    ITEM_CONVERSATION_FOLLOW,
    ITEM_CONVERSATION_SINGLE_IMAGE,
    ITEM_IMAGE,
    ITEM_PDF,
    ITEM_IMAGE_EXPANDED,
    ITEM_PDF_EXPANDED,
    ITEM_MEDIA_SMALL,
    ITEM_CONVERSATION_MULTIPLE_MEDIA,
    ITEM_CONVERSATION_SINGLE_PDF,
    ITEM_CONVERSATION_LINK,
    ITEM_CHATROOM_DATE,
    ITEM_POLL_MORE_OPTIONS,
    ITEM_IMAGE_SWIPE,
    ITEM_HOME_CHAT_ROOM,
    ITEM_DOCUMENT_SMALL,
    ITEM_EMPTY_VIEW,
    ITEM_CHAT_ROOM_ANNOUNCEMENT,
    ITEM_MEMBER_ACTION,
    ITEM_MANAGEMENT_RIGHT_PERMISSION,
    ITEM_CHATROOM_VIDEO,
    ITEM_CONVERSATION_SINGLE_VIDEO,
    ITEM_VIDEO,
    ITEM_VIDEO_SWIPE,
    ITEM_VIDEO_EXPANDED,
    ITEM_CONTENT_HEADER_VIEW,
    ITEM_HOME_LINE_BREAK_VIEW,
    ITEM_HOME_BLANK_SPACE_VIEW,
    ITEM_CHATROOM_LIST_SHIMMER_VIEW,
    ITEM_SEARCH_CHATROOM,
    ITEM_NO_SEARCH_RESULTS_VIEW,
    ITEM_SEARCH_CONTENT_HEADER_VIEW,
    ITEM_SEARCH_LINE_BREAK_VIEW,
    ITEM_SEARCH_MESSAGE,
    ITEM_CONVERSATION_LIST_SHIMMER_VIEW,
    ITEM_MESSAGE_REACTION,
    ITEM_CONVERSATION_SINGLE_GIF,
    ITEM_SEARCH_TITLE,
    ITEM_SINGLE_SHIMMER,
    ITEM_OVERFLOW_MENU_ITEM,
    ITEM_CONVERSATION_MULTIPLE_DOCUMENT,
    ITEM_DOCUMENT,
    ITEM_MEDIA_PICKER_AUDIO,
    ITEM_AUDIO_SMALL,
    ITEM_CONVERSATION_AUDIO,
    ITEM_AUDIO,
    ITEM_CREATE_CHATROOM_AUDIO,
    ITEM_CONVERSATION_VOICE_NOTE,
    ITEM_POLL_RESULT_USER,
    ITEM_HOME_FEED,
    ITEM_CHATROOM_PDF,
    ITEM_CHATROOM_IMAGE,
    ITEM_VIEW_PARTICIPANTS,
    ITEM_EXPLORE,
    ITEM_DM_FEED_EMPTY_DATA,
    ITEM_DIRECT_MESSAGE,
    ITEM_COMMUNITY_MEMBER,
    ITEM_CONVERSATION_CUSTOM_WIDGET,
    ITEM_CHANNEL_INVITE
)
@Retention(AnnotationRetention.SOURCE)
internal annotation class ViewType